variables:
  GIT_STRATEGY: none

fullTest:
  variables:
    GIT_STRATEGY: none
  script:
    - export PATH=/cvmfs/cms.cern.ch/common/:$PATH:/cvmfs/cms.cern.ch/share/overrides/bin:/afs/cern.ch/group/zh/bin:/afs/cern.ch/cms/caf/scripts:/cvmfs/cms.cern.ch/common:/cvmfs/cms.cern.ch/bin
    - which scram
    - pwd
    - wget --no-check-certificate https://raw.githubusercontent.com/ECALELFS/ECALELF/$BRANCH/setup_git.sh
    - git config --global user.github shervin86
    - git config --global user.name 'TESTBOT'
    - git config --global user.email 'shervin@cern.ch'
    - chmod +x setup_git.sh
    - ./setup_git.sh $CMSSW_VERSION $BRANCH
    - cd $CMSSW_VERSION/src/
    - eval `scramv1 runtime -sh`
    - cd Calibration/
    - git checkout releaseValidationUpdate
    - scram b 
    - cd EcalAlCaRecoProducers/
    - ./scripts/releaseValidation.sh


