import FWCore.ParameterSet.Config as cms

# ALCARECO collections
eleNewEnergiesProducer = cms.EDProducer('EleNewEnergiesProducer',
                                        electronCollection = cms.InputTag('gsfElectrons'),
                                        recHitCollectionEB = cms.InputTag("alCaIsolatedElectrons", "alcaBarrelHits"),
                                        recHitCollectionEE = cms.InputTag("alCaIsolatedElectrons", "alcaEndcapHits"),
                                        rhoFastJet = cms.InputTag('kt6PFJetsForRhoCorrection',"rho"),
                                        vertexCollection = cms.InputTag('offlinePrimaryVerticesWithBS'),
                                        BeamSpotCollection = cms.InputTag('offlineBeamSpot'),
                                        conversionCollection = cms.InputTag('allConversions'),
                                        isMC = cms.bool(False),
                                        regrPhoFile = cms.string('./data/gbrv3ph_52x.root'),
                                        regrEleFile = cms.string('./data/gbrv3ele_52x.root'),
                                        regrEleFile_fra = cms.string('nocorrection.root'),
                                        correctionFileName = cms.string(''),
                                        correctionType = cms.string(''),
                                        ptSplit = cms.bool(True),
                                        regrEleJoshV4_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v4_forest_ele.root'),
                                        regrPhoJoshV4_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v4_forest_ph.root'),
                                        regrEleJoshV5_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v5_forest_ele.root'),
                                        regrPhoJoshV5_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v5_forest_ph.root'),
                                        regrEleJoshV6_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v6_8TeV_forest_ele.root'),
                                        regrPhoJoshV6_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v6_8TeV_forest_ph.root'),
                                        regrEleJoshV7_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v7_8TeV_forest_ele.root'),
                                        regrPhoJoshV7_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v7_8TeV_forest_ph.root'),
                                        regrEleJoshV8_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v8_8TeV_forest_ele.root'),
                                        regrPhoJoshV8_SemiParamFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v8_8TeV_forest_ph.root'),
                                        regrEleJoshV6_SemiParam7TeVtrainFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v6_7TeV_forest_ele.root'),
                                        regrPhoJoshV6_SemiParam7TeVtrainFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v6_7TeV_forest_ph.root'),
                                        regrEleJoshV7_SemiParam7TeVtrainFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v7_7TeV_forest_ele.root'),
                                        regrPhoJoshV7_SemiParam7TeVtrainFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v7_7TeV_forest_ph.root'),
                                        regrEleJoshV8_SemiParam7TeVtrainFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v8_7TeV_forest_ele.root'),
                                        regrPhoJoshV8_SemiParam7TeVtrainFile = cms.string('src/HiggsAnalysis/GBRLikelihoodEGTools/data/regweights_v8_7TeV_forest_ph.root'),

                                        )
