ECALELF: EcalEleCalibLooper Class Reference
EcalEleCalibLooper Class Reference
ECAL TB 2006 calibration with matrix inversion technique.
#include <EcalEleCalibLooper.h>
Inherits EDLooper.
Public Member Functions
EcalEleCalibLooper (const edm::ParameterSet &)
ctor
~EcalEleCalibLooper ()
dtor
void beginOfJob ()
BeginOfJob.
void endOfJob ()
void startingNewLoop (unsigned int)
Status duringLoop (const edm::Event &, const edm::EventSetup &)
Status endOfLoop (const edm::EventSetup &, unsigned int iCounter)
Private Member Functions
int EBRegionId (const int, const int) const
Reg Id generator EB --— for the barrel.
int EERegionId (const int, const int) const
Gives the id of the region.
void EBRegionDefinition ()
DS EB Region Definition.
double giveLimit (int)
copes with the infinitives of the tangent
int EEregionCheck (const int, const int) const
returns zero if the coordinates are in the right place.
int EBregionCheck (const int eta, const int phi) const
Tells if you are in the region to be calibrated.
int etaShifter (const int) const
LP Change the coordinate system.
int EEregionsNum () const
DS Number of regions in EE.
int EBregionsNum () const
DS number of regions in EB.
Private Attributes
edm::InputTag m_barrelAlCa
EcalBarrel Input Collection name.
edm::InputTag m_endcapAlCa
EcalEndcap Input Collection name.
int m_recoWindowSidex
reconstruction window size
int m_etaWidth
eta size of the sub-matrix
int m_phiWidthEB
eta size of the additive border to the sub-matrix
int m_etaStart
phi size of the additive border to the sub-matrix
int m_etaEnd
eta end of the region of interest
int m_phiStartEB
phi start of the region of interest
int m_phiEndEB
phi end of the region of interest
int m_radStart
DS For the EE.
int m_maxSelectedNumPerXtal
maximum number of events per crystal
std::vector< VEcalCalibBlock * > m_EcalCalibBlocks
single blocks calibrators
double m_minEnergyPerCrystal
minimum energy per crystal cut
double m_maxEnergyPerCrystal
maximum energy per crystal cut
double m_minCoeff
minimum coefficient accepted (RAW)
double m_maxCoeff
maximum coefficient accepted (RAW)
int m_usingBlockSolver
to exclude the blocksolver
EcalIntercalibConstantMap m_barrelMap
the maps of recalib coeffs
unsigned int m_loops
DS sets the number of loops to do.
edm::InputTag m_ElectronLabel
To take the electrons.
Detailed Description
ECAL TB 2006 calibration with matrix inversion technique.
Author
Constructor & Destructor Documentation
EcalEleCalibLooper::EcalEleCalibLooper (const edm::ParameterSet & iConfig) explicit
ctor
LP ctor.
References EBRegionDefinition(), EBregionsNum(), EEregionsNum(), m_barrelMap, m_EcalCalibBlocks, m_etaEnd, m_etaStart, m_etaWidth, m_maxEnergyPerCrystal, m_minEnergyPerCrystal, m_radStart, and m_recoWindowSidex.
EcalEleCalibLooper::~EcalEleCalibLooper ()
dtor
LP destructor.
References m_EcalCalibBlocks.
Member Function Documentation
void EcalEleCalibLooper::endOfJob ()
LP endOfJob writes the coefficients in the xml format and exits
References m_barrelMap.
void EcalEleCalibLooper::startingNewLoop (unsigned int ciclo)
startingNewLoop empties the map of the calibBlock so that it can be filled
References m_EcalCalibBlocks.
edm::EDLooper::Status EcalEleCalibLooper::duringLoop (const edm::Event & iEvent, const edm::EventSetup & iSetup)
duringLoop return the status Kcontinue, fills the calibBlock with the recHits
References m_barrelAlCa, m_barrelMap, m_EcalCalibBlocks, m_ElectronLabel, m_endcapAlCa, and m_maxSelectedNumPerXtal.
edm::EDLooper::Status EcalEleCalibLooper::endOfLoop (const edm::EventSetup & dumb, unsigned int iCounter)
EndOfLoop Return kContinue if there's still another loop to be done; otherwise stops returnig kStop; Takes the coefficients solving the calibBlock;
References m_barrelMap, m_EcalCalibBlocks, m_loops, m_maxCoeff, m_minCoeff, and m_usingBlockSolver.
Member Data Documentation
int EcalEleCalibLooper::m_phiWidthEB private
eta size of the additive border to the sub-matrix
phi size of the sub-matrix
Referenced by EBRegionId(), and EBregionsNum().
int EcalEleCalibLooper::m_etaStart private
phi size of the additive border to the sub-matrix
eta start of the region of interest
Referenced by EBregionCheck(), EBRegionId(), EBregionsNum(), and EcalEleCalibLooper().
The documentation for this class was generated from the following files:
EcalCalibAlgos/interface/EcalEleCalibLooper.h
EcalCalibAlgos/src/EcalEleCalibLooper.cc