ECALELF: InvRingCalib Class Reference
InvRingCalib Class Reference
ECAL TB 2006 calibration with matrix inversion technique.
#include <InvRingCalib.h>
Inherits EDLooper.
Public Member Functions
InvRingCalib (const edm::ParameterSet &)
ctor
~InvRingCalib ()
dtor
void beginOfJob ()
BeginOfJob.
void startingNewLoop (unsigned int)
startingNewLoop
Status duringLoop (const edm::Event &, const edm::EventSetup &)
duringLoop
Private Member Functions
int EERegionNum () const
The number of regions in EE.
int EBRegionNum () const
Number of regions in EB.
void EBRegionDef ()
Defines the regions in the barrel.
void EERingDef (const edm::EventSetup &)
Defines the rins in the endcap.
void EERegionDef ()
Defines the regions in the endcap.
void RegPrepare ()
Prepares the EB regions;.
int EBRegId (const int)
Gives back in which region you are:
int EERegId (int)
gives back in which region of the endcap you are.
Private Attributes
VFillMap * m_MapFiller
The class that fills the map!
edm::InputTag m_barrelAlCa
EcalBarrel Input Collection name.
edm::InputTag m_endcapAlCa
EcalEndcap Input Collection name.
edm::InputTag m_ElectronLabel
To take the electrons.
int m_recoWindowSidex
reconstruction window size
double m_minEnergyPerCrystal
minimum energy per crystal cut
double m_maxEnergyPerCrystal
maximum energy per crystal cut
int m_etaStart
eta start of the zone of interest
int m_etaEnd
eta end of the zone of interest
int m_etaWidth
eta size of the regions
int m_maxSelectedNumPerRing
maximum number of events per Ring
std::map< int, int > m_RingNumOfHits
number of events already read per Ring
std::vector< VEcalCalibBlock * > m_IMACalibBlocks
single blocks calibrators
double m_minCoeff
minimum coefficient accepted (RAW)
double m_maxCoeff
maximum coefficient accepted (RAW)
int m_usingBlockSolver
to exclude the blocksolver
std::map< int, GlobalPoint > m_cellPos
position of the cell, borders, coords etc...
EcalIntercalibConstantMap m_barrelMap
unsigned int m_loops
LP sets the number of loops to do.
int m_startRing
LP define the EE region to calibrate.
std::map< int, int > m_xtalRing
association map between Raw detIds and Rings
std::map< int, int > m_xtalRegionId
association map between raw detIds and Region
std::map< int, int > m_RinginRegion
association map between raw detIds and the number of the ring inside the region
std::vector< DetId > m_barrelCells
geometry things used all over the file
std::string m_EBcoeffFile
coeffs filenames
int m_EEZone
endcap zone to be calibrated
std::map< int, int > m_Reg
EB regions vs. eta index.
Detailed Description
ECAL TB 2006 calibration with matrix inversion technique.
Author
Constructor & Destructor Documentation
InvRingCalib::~InvRingCalib ()
dtor
destructor
Member Function Documentation
int InvRingCalib::EBRegId (const int ieta) private
Gives back in which region you are:
gives the region Id given ieta
References m_etaEnd, and m_Reg.
Referenced by EBRegionDef().
int InvRingCalib::EBRegionNum () const private
Number of regions in EB.
number of Ring in EB
References m_etaEnd, m_etaStart, and m_etaWidth.
Referenced by EERegionDef(), and InvRingCalib().
int InvRingCalib::EERegId (int id) private
gives back in which region of the endcap you are.
Gives the Id of the region given the id of the xtal.
References m_EEZone, m_etaWidth, m_RinginRegion, and m_startRing.
Referenced by EERegionDef().
void InvRingCalib::EERegionDef () private
Defines the regions in the endcap.
Loops over all the endcap xtals and sets for each xtal the value of the region the xtal is in, and the ringNumber inside the region
References EBRegionNum(), EERegId(), EERegionNum(), and m_xtalRegionId.
Referenced by duringLoop().
int InvRingCalib::EERegionNum () const inline private
The number of regions in EE.
Number of Regions in EE.
References m_etaWidth, and m_startRing.
Referenced by EERegionDef(), and InvRingCalib().
void InvRingCalib::EERingDef (const edm::EventSetup & iSetup) private
Defines the rins in the endcap.
EE ring definition.
References m_cellPos.
Referenced by duringLoop().
void InvRingCalib::RegPrepare () private
Prepares the EB regions;.
Divides the barrel in region, necessary to take into account the missing 0 xtal
References m_etaEnd, m_etaStart, m_etaWidth, and m_Reg.
Referenced by EBRegionDef().
Member Data Documentation
EcalIntercalibConstantMap InvRingCalib::m_barrelMap private
association map between coeff and ring coeffs for the single xtals
Referenced by duringLoop().
The documentation for this class was generated from the following files:
EcalCalibAlgos/interface/InvRingCalib.h
EcalCalibAlgos/src/InvRingCalib.cc